package Semaforo;

import Departamentos.Departamentos;
import Accidentes.Configuracion;
import Configuracion.Settings;
import Accidentes.AgregarIncidente;
import Accidentes.AgregarAccidente;
import Departamentos.AgregarDepartamento;
import Usuarios.AgregarUsuario;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import static java.lang.Integer.parseInt;
import java.util.Date;
import java.sql.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cliente
 */
public class SemaforoForm extends javax.swing.JFrame {

    public final Settings sett = new Settings();
    public int NumeroAccidentes;
    public int DiasSinAccidentes;

    public SemaforoForm() {
        initComponents();
    }

    /**
     * Creates new form SemaforoForm
     *
     * @param NumeroAccidentes
     */
    public SemaforoForm(int NumeroAccidentes) {
        initComponents();
        this.NumeroAccidentes = NumeroAccidentes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tablero De Seguridad Industrial");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Llevamos 0 dias sin accidentes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departamento", "Accidentes", "Incidentes", "Dias sin accidentes"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Agregar Accidente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Agregar Incidente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Agregar Departamento");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Configuracion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setText("Agregar Usuario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //NumeroAccidentes Accidentes1 = new NumeroAccidentes();
        //Accidentes1.setVisible(true);

        Connection conn;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn
                    = DriverManager.getConnection("jdbc:mysql://localhost/semaforo?"
                            + "user=root&password=4b0g4d0sf@M18");

            // Do something with the Connection
            Statement stmt = null;
            ResultSet rs = null;

            try {
                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT count(*) FROM accidentes");
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnsNumber = rsmd.getColumnCount();

                while (rs.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        if (i > 1) {
                            System.out.print(",  ");
                        }
                        String columnValue = rs.getString(i);
                        this.NumeroAccidentes = Integer.parseInt(rs.getString(1));
                        //System.out.print(columnValue + " " + rsmd.getColumnName(i));
                    }

                }

                rs = stmt.executeQuery("SELECT datediff(created_at, CURRENT_TIMESTAMP) FROM accidentes order by id DESC LIMIT 1");

                while (rs.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        if (i > 1) {
                            System.out.print(",  ");
                        }
                        String columnValue = rs.getString(i);
                        this.DiasSinAccidentes = Integer.parseInt(rs.getString(1));
                        this.DiasSinAccidentes = Math.abs(this.DiasSinAccidentes);
                        //System.out.print(columnValue + " " + rsmd.getColumnName(i));
                    }
                }

            } catch (SQLException ex) {
                // handle any errors
                System.out.println("SQLException: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("VendorError: " + ex.getErrorCode());
            } finally {
                // it is a good idea to release
                // resources in a finally{} block
                // in reverse-order of their creation
                // if they are no-longer needed

                if (rs != null) {
                    try {
                        rs.close();
                    } catch (SQLException sqlEx) {
                    } // ignore

                    rs = null;
                }

                if (stmt != null) {
                    try {
                        stmt.close();
                    } catch (SQLException sqlEx) {
                    } // ignore

                    stmt = null;
                }
            }

        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SemaforoForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        //int Accidentes = 6;
        Date dateobj = new Date();
        LocalDate localDate = dateobj.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int month = localDate.getMonthValue();
        String monthString = GetMonth(month);
        String Ruta = "C:\\Users\\cliente\\Documents\\NetBeansProjects\\semaforo\\src\\main\\java\\com\\itcj\\semaforo\\";
        jLabel2.setText(dateobj.toString());
        jLabel2.setText(monthString);
        jLabel4.setText("Llevamos " + this.NumeroAccidentes + " accidentes");
        jLabel5.setText("Llevamos " + this.DiasSinAccidentes + " dias sin accidentes");
        System.out.println(this.NumeroAccidentes);
        if (this.NumeroAccidentes <= this.sett.GreenValue) {
            jLabel3.setIcon(new javax.swing.ImageIcon(Ruta + "semaforo_ok.png"));

        } else if (this.NumeroAccidentes > this.sett.GreenValue && this.NumeroAccidentes <= this.sett.YellowValue) {
            jLabel3.setIcon(new javax.swing.ImageIcon(Ruta + "semaforo_warning.png"));

        } else if (this.NumeroAccidentes > this.sett.YellowValue) {
            jLabel3.setIcon(new javax.swing.ImageIcon(Ruta + "semaforo_danger.png"));

        }

        LoadTable();
        CreateCalendar();

    }//GEN-LAST:event_formComponentShown

    public void CreateCalendar() {
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        int lastday = cal.getActualMaximum(Calendar.DATE);
        cal.add(Calendar.DATE, -cal.get(Calendar.DATE) + 1);
        int offset = cal.get(Calendar.DAY_OF_WEEK) - 1;

        jPanel1.setLayout(new GridLayout(0, 7));
        ArrayList<JLabel> labelArray = new ArrayList<JLabel>();
        for (int i = 0; i < offset; i++) {
            labelArray.add(new JLabel(" "));
        }

        for (int i = 1; i <= lastday; i++) {
            labelArray.add(new JLabel(String.valueOf(i)));
        }

        Iterator<JLabel> ite = labelArray.iterator();

        while (ite.hasNext()) {
            JLabel label = (JLabel) ite.next();
            label.setHorizontalAlignment(JLabel.TRAILING);
            jPanel1.add(label);
        }

        getContentPane().add(jPanel1, BorderLayout.CENTER);

    }

    public void LoadTable() {
        //Obtenemos la lista de departamentos para cargarlos a la tabla
        Departamentos departamentos = new Departamentos();
        String[][] Departamentos = departamentos.GetDepartamentos();
        int[] Totales = new int[3];
        String Accidentes, Incidentes, DiasSinAccidentes;
        DiasSinAccidentes = "✓";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < Departamentos.length; i++) {
            int[] AccInc = new int[2];
            AccInc = departamentos.GetAccidentesAndIncidentes(parseInt(Departamentos[i][0]));
            if (AccInc[0] != 0) {
                Accidentes = Integer.toString(AccInc[0]);
                Totales[0] = Totales[0] + AccInc[0];
            } else {
                Accidentes = "✓";
            }

            if (AccInc[1] != 0) {
                Incidentes = Integer.toString(AccInc[1]);
                Totales[1] = Totales[1] + AccInc[1];
            } else {
                Incidentes = "✓";
            }

            int ToCompareDias = Math.abs(AccInc[2]);
            DiasSinAccidentes = Integer.toString(ToCompareDias);

            model.addRow(new Object[]{Departamentos[i][1], Accidentes, Incidentes, DiasSinAccidentes});
        }

        model.addRow(new Object[]{"TOTAL", Totales[0], Totales[1], "N/A"});
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Configuracion conf = new Configuracion();
        conf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private String GetMonth(int month) {
        if (month == 1) {
            return "Enero";
        } else if (month == 2) {
            return "Febrero";
        } else if (month == 3) {
            return "Marzo";
        } else if (month == 4) {
            return "Abril";
        } else if (month == 5) {
            return "Mayo";
        } else if (month == 6) {
            return "Junio";
        } else if (month == 7) {
            return "Julio";
        } else if (month == 8) {
            return "Agosto";
        } else if (month == 9) {
            return "Septiembre";
        } else if (month == 10) {
            return "Octubre";
        } else if (month == 11) {
            return "Noviembre";
        } else if (month == 12) {
            return "Diciembre";
        } else {
            return "Mes Desconocido";
        }
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AgregarAccidente Agregar = new AgregarAccidente();
        Agregar.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AgregarDepartamento AgregarD = new AgregarDepartamento();
        AgregarD.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        AgregarIncidente AgregarI = new AgregarIncidente();
        AgregarI.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AgregarUsuario AgregarU = new AgregarUsuario();
        AgregarU.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown

    }//GEN-LAST:event_jPanel1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemaforoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemaforoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemaforoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemaforoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new SemaforoForm().setVisible(true);

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void parseString(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
